export const LOGIN_PENDING  = 'LOGIN_PENDING';
export const LOGIN_REJECTED  = 'LOGIN_REJECTED';
export const LOGIN_FULLFILLED  = 'LOGIN_FULLFILLED';

export const FORGET_PASSWORD_PENDING  = 'FORGET_PASSWORD_PENDING';
export const FORGET_PASSWORD_REJECTED  = 'FORGET_PASSWORD_REJECTED';
export const FORGET_PASSWORD_FULLFILLED  = 'FORGET_PASSWORD_FULLFILLED';
export const LOGOUT = 'LOGOUT';

export const GET_ALL_ELEPHANTS_PENDING  = 'GET_ALL_ELEPHANTS_PENDING';
export const GET_ALL_ELEPHANTS_REJECTED = 'GET_ALL_ELEPHANTS_REJECTED';
export const GET_ALL_ELEPHANTS_FULLFILLED = 'GET_ALL_ELEPHANTS_FULLFILLED';

export const CREATE_ELEPHANT_PENDING = 'CREATE_ELEPHANT_PENDING';
export const CREATE_ELEPHANT_REJECTED = 'CREATE_ELEPHANT_REJECTED';
export const CREATE_ELEPHANT_FULLFILLED = 'CREATE_ELEPHANT_FULLFILLED';

export const FIND_SPECIFIC_ELEPHANT_PENDING = 'FIND_SPECIFIC_ELEPHANT_PENDING';
export const FIND_SPECIFIC_ELEPHANT_REJECTED = 'FIND_SPECIFIC_ELEPHANT_REJECTED';
export const FIND_SPECIFIC_ELEPHANT_FULLFILLED = 'FIND_SPECIFIC_ELEPHANT_FULLFILLED';

